/**
 * Customer Domain Components
 *
 * Barrel export for customer-related UI components.
 */
export { CustomerDirectory } from './customer-directory'
export { CustomerTable, type CustomerTableData } from './customer-table'
export { CustomerFilters, type CustomerFiltersState } from './customer-filters'
export { Customer360View } from './customer-360-view'
export { MetricsDashboard } from './metrics-dashboard'
export { ActivityTimeline } from './activity-timeline'
export { CustomerForm } from './customer-form'
export { CustomerWizard } from './customer-wizard'
export { ContactManager, type ManagedContact } from './contact-manager'
export { AddressManager, type ManagedAddress } from './address-manager'
export { HealthDashboard } from './health-dashboard'
export { HealthScoreGauge, HealthScoreBadge } from './health-score-gauge'
export { HealthRecommendations } from './health-recommendations'
export { RiskAlerts } from './risk-alerts'
export { SegmentBuilder } from './segment-builder'
export { SegmentManager } from './segment-manager'
export { SegmentAnalytics } from './segment-analytics'
export { CommunicationTimeline } from './communication-timeline'
export { CommunicationTemplates } from './communication-templates'
export { BulkCommunications } from './bulk-communications'
export { AnalyticsDashboard } from './analytics-dashboard'
export { LifecycleAnalytics } from './lifecycle-analytics'
export { ValueAnalysis } from './value-analysis'
export { MergeWizard } from './merge-wizard'
export { DuplicateDetection } from './duplicate-detection'
export { MergeHistory } from './merge-history'
export { BulkSelector, type SelectableCustomer } from './bulk-selector'
export { BulkOperations } from './bulk-operations'
export { BulkImport } from './bulk-import'
export { BulkExport } from './bulk-export'
export { DuplicateWarningPanel, CompactDuplicateWarning } from './duplicate-warning-panel'
export { DuplicateScanButton } from './duplicate-scan-button'
export { DuplicateComparison } from './duplicate-comparison'
export { DuplicateReviewQueue } from './duplicate-review-queue'
