/**
 * Report Summary PDF Template
 *
 * Generates a branded summary report with key metrics.
 */
import { Document, Page, StyleSheet, View, Text } from "@react-pdf/renderer";
import { OrgDocumentProvider, useOrgDocument } from "../../context";
import { FixedDocumentHeader, PageNumber } from "../../components";
import {
  colors,
  pageMargins,
  fixedHeaderClearance,
  spacing,
  borderRadius,
  fontSize,
  lineHeight,
  tabularNums,
  FONT_FAMILY,
  FONT_WEIGHTS,
  formatDateForPdf,
} from "../../components/theme";
import type { DocumentOrganization } from "../../types";

// ============================================================================
// TYPES
// ============================================================================

export interface ReportSummaryMetric {
  label: string;
  value: string;
}

export interface ReportSummaryDocumentData {
  reportName: string;
  dateFrom: Date;
  dateTo: Date;
  metrics: ReportSummaryMetric[];
  generatedAt?: Date;
}

export interface ReportSummaryPdfDocumentProps {
  organization: DocumentOrganization;
  data: ReportSummaryDocumentData;
}

// ============================================================================
// STYLES
// ============================================================================

const styles = StyleSheet.create({
  page: {
    paddingTop: pageMargins.top,
    paddingBottom: pageMargins.bottom,
    paddingLeft: pageMargins.left,
    paddingRight: pageMargins.right,
    backgroundColor: colors.background.white,
    fontSize: fontSize.base,
  },
  content: {
    flex: 1,
    marginTop: fixedHeaderClearance,
  },
  header: {
    marginBottom: spacing.xl,
  },
  title: {
    fontSize: fontSize["2xl"],
    fontFamily: FONT_FAMILY,
    fontWeight: FONT_WEIGHTS.bold,
    color: colors.text.primary,
  },
  subtitle: {
    marginTop: spacing.xs,
    fontFamily: FONT_FAMILY,
    color: colors.text.muted,
    fontSize: fontSize.base,
    lineHeight: lineHeight.relaxed,
  },
  card: {
    borderWidth: 1,
    borderColor: colors.border.light,
    borderRadius: borderRadius.md,
    padding: spacing.lg,
    backgroundColor: colors.background.white,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border.light,
    paddingBottom: spacing.sm,
    marginBottom: spacing.sm,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border.light,
  },
  cellLabel: {
    flex: 1,
    fontFamily: FONT_FAMILY,
    color: colors.text.primary,
    lineHeight: lineHeight.relaxed,
  },
  cellValue: {
    width: 140,
    fontFamily: FONT_FAMILY,
    textAlign: "right",
    color: colors.text.primary,
    fontWeight: FONT_WEIGHTS.semibold,
    ...tabularNums,
  },
  footer: {
    marginTop: spacing.lg,
    fontFamily: FONT_FAMILY,
    color: colors.text.muted,
    fontSize: fontSize.sm,
  },
});

// ============================================================================
// INTERNAL COMPONENT
// ============================================================================

function ReportSummaryContent({ data }: { data: ReportSummaryDocumentData }) {
  const { organization, locale } = useOrgDocument();
  const generatedAt = data.generatedAt ?? new Date();

  return (
    <Page size="A4" style={styles.page}>
      <FixedDocumentHeader
        orgName={organization.name}
        documentType="Report"
        documentNumber={data.reportName}
      />
      <View style={styles.content}>
      <View style={styles.header}>
        <Text style={styles.title}>{data.reportName}</Text>
        <Text style={styles.subtitle}>
          {organization.name} • {formatDateForPdf(data.dateFrom, locale)} -{" "}
          {formatDateForPdf(data.dateTo, locale)}
        </Text>
        <Text style={styles.subtitle}>
          Generated: {formatDateForPdf(generatedAt, locale)}
        </Text>
      </View>

      <View style={styles.card}>
        <View style={styles.tableHeader}>
          <Text style={styles.cellLabel}>Metric</Text>
          <Text style={styles.cellValue}>Value</Text>
        </View>
        {data.metrics.map((metric) => (
          <View key={metric.label} style={styles.tableRow}>
            <Text style={styles.cellLabel}>{metric.label}</Text>
            <Text style={styles.cellValue}>{metric.value}</Text>
          </View>
        ))}
      </View>

      <Text style={styles.footer}>
        This report was generated by Renoz CRM.
      </Text>
      </View>

      <PageNumber documentNumber={data.reportName} />
    </Page>
  );
}

// ============================================================================
// EXPORTED COMPONENT
// ============================================================================

export function ReportSummaryPdfDocument({
  organization,
  data,
}: ReportSummaryPdfDocumentProps) {
  return (
    <OrgDocumentProvider organization={organization}>
      <Document
        title={data.reportName}
        author={organization.name}
        subject={`${data.reportName} summary`}
        creator="Renoz CRM"
        language="en-AU"
        keywords={`report, ${data.reportName}`}
      >
        <ReportSummaryContent data={data} />
      </Document>
    </OrgDocumentProvider>
  );
}
