/**
 * Report Summary PDF Template
 *
 * Generates a branded summary report with key metrics.
 */
import { Document, Page, StyleSheet, View, Text } from "@react-pdf/renderer";
import { OrgDocumentProvider, useOrgDocument } from "../../context";
import { PageNumber } from "../../components/footer";
import { colors, pageMargins, spacing, formatDateForPdf } from "../../components/theme";
import type { DocumentOrganization } from "../../types";

// ============================================================================
// TYPES
// ============================================================================

export interface ReportSummaryMetric {
  label: string;
  value: string;
}

export interface ReportSummaryDocumentData {
  reportName: string;
  dateFrom: Date;
  dateTo: Date;
  metrics: ReportSummaryMetric[];
  generatedAt?: Date;
}

export interface ReportSummaryPdfDocumentProps {
  organization: DocumentOrganization;
  data: ReportSummaryDocumentData;
}

// ============================================================================
// STYLES
// ============================================================================

const styles = StyleSheet.create({
  page: {
    paddingTop: pageMargins.top,
    paddingBottom: pageMargins.bottom,
    paddingLeft: pageMargins.left,
    paddingRight: pageMargins.right,
    backgroundColor: colors.background.white,
    fontSize: 11,
  },
  header: {
    marginBottom: spacing.lg,
  },
  title: {
    fontSize: 20,
    fontWeight: 700,
    color: colors.text.primary,
  },
  subtitle: {
    marginTop: spacing.xs,
    color: colors.text.muted,
    fontSize: 11,
  },
  card: {
    borderWidth: 1,
    borderColor: colors.border.light,
    borderRadius: 8,
    padding: spacing.lg,
    backgroundColor: colors.background.white,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
    paddingBottom: spacing.sm,
    marginBottom: spacing.sm,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  cellLabel: {
    flex: 1,
    color: colors.text.primary,
  },
  cellValue: {
    width: 140,
    textAlign: "right",
    color: colors.text.primary,
    fontWeight: 600,
  },
  footer: {
    marginTop: spacing.lg,
    color: colors.text.muted,
    fontSize: 10,
  },
});

// ============================================================================
// INTERNAL COMPONENT
// ============================================================================

function ReportSummaryContent({ data }: { data: ReportSummaryDocumentData }) {
  const { organization, locale } = useOrgDocument();
  const generatedAt = data.generatedAt ?? new Date();

  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{data.reportName}</Text>
        <Text style={styles.subtitle}>
          {organization.name} • {formatDateForPdf(data.dateFrom, locale)} -{" "}
          {formatDateForPdf(data.dateTo, locale)}
        </Text>
        <Text style={styles.subtitle}>
          Generated: {formatDateForPdf(generatedAt, locale)}
        </Text>
      </View>

      <View style={styles.card}>
        <View style={styles.tableHeader}>
          <Text style={styles.cellLabel}>Metric</Text>
          <Text style={styles.cellValue}>Value</Text>
        </View>
        {data.metrics.map((metric) => (
          <View key={metric.label} style={styles.tableRow}>
            <Text style={styles.cellLabel}>{metric.label}</Text>
            <Text style={styles.cellValue}>{metric.value}</Text>
          </View>
        ))}
      </View>

      <Text style={styles.footer}>
        This report was generated by Renoz CRM.
      </Text>

      <PageNumber />
    </Page>
  );
}

// ============================================================================
// EXPORTED COMPONENT
// ============================================================================

export function ReportSummaryPdfDocument({
  organization,
  data,
}: ReportSummaryPdfDocumentProps) {
  return (
    <OrgDocumentProvider organization={organization}>
      <Document
        title={data.reportName}
        author={organization.name}
        subject={`${data.reportName} summary`}
        creator="Renoz CRM"
        language="en-AU"
        keywords={`report, ${data.reportName}`}
      >
        <ReportSummaryContent data={data} />
      </Document>
    </OrgDocumentProvider>
  );
}
