/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPipelineIndexRouteImport } from './routes/_authenticated/pipeline/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedMobileIndexRouteImport } from './routes/_authenticated/mobile/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedActivitiesIndexRouteImport } from './routes/_authenticated/activities/index'
import { Route as AuthenticatedSettingsCategoriesRouteImport } from './routes/_authenticated/settings/categories'
import { Route as AuthenticatedSettingsApiTokensRouteImport } from './routes/_authenticated/settings/api-tokens'
import { Route as AuthenticatedReportsPipelineForecastRouteImport } from './routes/_authenticated/reports/pipeline-forecast'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products/$productId'
import { Route as AuthenticatedPipelineOpportunityIdRouteImport } from './routes/_authenticated/pipeline/$opportunityId'
import { Route as AuthenticatedOrdersFulfillmentRouteImport } from './routes/_authenticated/orders/fulfillment'
import { Route as AuthenticatedOrdersCreateRouteImport } from './routes/_authenticated/orders/create'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders/$orderId'
import { Route as AuthenticatedMobileReceivingRouteImport } from './routes/_authenticated/mobile/receiving'
import { Route as AuthenticatedMobilePickingRouteImport } from './routes/_authenticated/mobile/picking'
import { Route as AuthenticatedMobileCountingRouteImport } from './routes/_authenticated/mobile/counting'
import { Route as AuthenticatedInventoryReceivingRouteImport } from './routes/_authenticated/inventory/receiving'
import { Route as AuthenticatedInventoryLocationsRouteImport } from './routes/_authenticated/inventory/locations'
import { Route as AuthenticatedInventoryForecastingRouteImport } from './routes/_authenticated/inventory/forecasting'
import { Route as AuthenticatedInventoryDashboardRouteImport } from './routes/_authenticated/inventory/dashboard'
import { Route as AuthenticatedInventoryCountsRouteImport } from './routes/_authenticated/inventory/counts'
import { Route as AuthenticatedInventoryAnalyticsRouteImport } from './routes/_authenticated/inventory/analytics'
import { Route as AuthenticatedInventoryAlertsRouteImport } from './routes/_authenticated/inventory/alerts'
import { Route as AuthenticatedInventoryItemIdRouteImport } from './routes/_authenticated/inventory/$itemId'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers/new'
import { Route as AuthenticatedCustomersDuplicatesRouteImport } from './routes/_authenticated/customers/duplicates'
import { Route as AuthenticatedCustomersCommunicationsRouteImport } from './routes/_authenticated/customers/communications'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'
import { Route as AuthenticatedReportsCustomersIndexRouteImport } from './routes/_authenticated/reports/customers/index'
import { Route as AuthenticatedCustomersSegmentsIndexRouteImport } from './routes/_authenticated/customers/segments/index'
import { Route as AuthenticatedAdminActivitiesIndexRouteImport } from './routes/_authenticated/admin/activities/index'
import { Route as AuthenticatedProductsProductIdEditRouteImport } from './routes/_authenticated/products/$productId/edit'
import { Route as AuthenticatedCustomersCustomerIdEditRouteImport } from './routes/_authenticated/customers/$customerId_.edit'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPipelineIndexRoute =
  AuthenticatedPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMobileIndexRoute =
  AuthenticatedMobileIndexRouteImport.update({
    id: '/mobile/',
    path: '/mobile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActivitiesIndexRoute =
  AuthenticatedActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCategoriesRoute =
  AuthenticatedSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsApiTokensRoute =
  AuthenticatedSettingsApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReportsPipelineForecastRoute =
  AuthenticatedReportsPipelineForecastRouteImport.update({
    id: '/reports/pipeline-forecast',
    path: '/reports/pipeline-forecast',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPipelineOpportunityIdRoute =
  AuthenticatedPipelineOpportunityIdRouteImport.update({
    id: '/pipeline/$opportunityId',
    path: '/pipeline/$opportunityId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersFulfillmentRoute =
  AuthenticatedOrdersFulfillmentRouteImport.update({
    id: '/orders/fulfillment',
    path: '/orders/fulfillment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersCreateRoute =
  AuthenticatedOrdersCreateRouteImport.update({
    id: '/orders/create',
    path: '/orders/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMobileReceivingRoute =
  AuthenticatedMobileReceivingRouteImport.update({
    id: '/mobile/receiving',
    path: '/mobile/receiving',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMobilePickingRoute =
  AuthenticatedMobilePickingRouteImport.update({
    id: '/mobile/picking',
    path: '/mobile/picking',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMobileCountingRoute =
  AuthenticatedMobileCountingRouteImport.update({
    id: '/mobile/counting',
    path: '/mobile/counting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryReceivingRoute =
  AuthenticatedInventoryReceivingRouteImport.update({
    id: '/inventory/receiving',
    path: '/inventory/receiving',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryLocationsRoute =
  AuthenticatedInventoryLocationsRouteImport.update({
    id: '/inventory/locations',
    path: '/inventory/locations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryForecastingRoute =
  AuthenticatedInventoryForecastingRouteImport.update({
    id: '/inventory/forecasting',
    path: '/inventory/forecasting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryDashboardRoute =
  AuthenticatedInventoryDashboardRouteImport.update({
    id: '/inventory/dashboard',
    path: '/inventory/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryCountsRoute =
  AuthenticatedInventoryCountsRouteImport.update({
    id: '/inventory/counts',
    path: '/inventory/counts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAnalyticsRoute =
  AuthenticatedInventoryAnalyticsRouteImport.update({
    id: '/inventory/analytics',
    path: '/inventory/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryAlertsRoute =
  AuthenticatedInventoryAlertsRouteImport.update({
    id: '/inventory/alerts',
    path: '/inventory/alerts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryItemIdRoute =
  AuthenticatedInventoryItemIdRouteImport.update({
    id: '/inventory/$itemId',
    path: '/inventory/$itemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersDuplicatesRoute =
  AuthenticatedCustomersDuplicatesRouteImport.update({
    id: '/customers/duplicates',
    path: '/customers/duplicates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCommunicationsRoute =
  AuthenticatedCustomersCommunicationsRouteImport.update({
    id: '/customers/communications',
    path: '/customers/communications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsCustomersIndexRoute =
  AuthenticatedReportsCustomersIndexRouteImport.update({
    id: '/reports/customers/',
    path: '/reports/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersSegmentsIndexRoute =
  AuthenticatedCustomersSegmentsIndexRouteImport.update({
    id: '/customers/segments/',
    path: '/customers/segments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminActivitiesIndexRoute =
  AuthenticatedAdminActivitiesIndexRouteImport.update({
    id: '/admin/activities/',
    path: '/admin/activities/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductIdEditRoute =
  AuthenticatedProductsProductIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProductsProductIdRoute,
  } as any)
const AuthenticatedCustomersCustomerIdEditRoute =
  AuthenticatedCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId_/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/customers/communications': typeof AuthenticatedCustomersCommunicationsRoute
  '/customers/duplicates': typeof AuthenticatedCustomersDuplicatesRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/inventory/$itemId': typeof AuthenticatedInventoryItemIdRoute
  '/inventory/alerts': typeof AuthenticatedInventoryAlertsRoute
  '/inventory/analytics': typeof AuthenticatedInventoryAnalyticsRoute
  '/inventory/counts': typeof AuthenticatedInventoryCountsRoute
  '/inventory/dashboard': typeof AuthenticatedInventoryDashboardRoute
  '/inventory/forecasting': typeof AuthenticatedInventoryForecastingRoute
  '/inventory/locations': typeof AuthenticatedInventoryLocationsRoute
  '/inventory/receiving': typeof AuthenticatedInventoryReceivingRoute
  '/mobile/counting': typeof AuthenticatedMobileCountingRoute
  '/mobile/picking': typeof AuthenticatedMobilePickingRoute
  '/mobile/receiving': typeof AuthenticatedMobileReceivingRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/orders/create': typeof AuthenticatedOrdersCreateRoute
  '/orders/fulfillment': typeof AuthenticatedOrdersFulfillmentRoute
  '/pipeline/$opportunityId': typeof AuthenticatedPipelineOpportunityIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRouteWithChildren
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/reports/pipeline-forecast': typeof AuthenticatedReportsPipelineForecastRoute
  '/settings/api-tokens': typeof AuthenticatedSettingsApiTokensRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/mobile/': typeof AuthenticatedMobileIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/pipeline/': typeof AuthenticatedPipelineIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/customers/$customerId/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/admin/activities/': typeof AuthenticatedAdminActivitiesIndexRoute
  '/customers/segments/': typeof AuthenticatedCustomersSegmentsIndexRoute
  '/reports/customers/': typeof AuthenticatedReportsCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/customers/communications': typeof AuthenticatedCustomersCommunicationsRoute
  '/customers/duplicates': typeof AuthenticatedCustomersDuplicatesRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/inventory/$itemId': typeof AuthenticatedInventoryItemIdRoute
  '/inventory/alerts': typeof AuthenticatedInventoryAlertsRoute
  '/inventory/analytics': typeof AuthenticatedInventoryAnalyticsRoute
  '/inventory/counts': typeof AuthenticatedInventoryCountsRoute
  '/inventory/dashboard': typeof AuthenticatedInventoryDashboardRoute
  '/inventory/forecasting': typeof AuthenticatedInventoryForecastingRoute
  '/inventory/locations': typeof AuthenticatedInventoryLocationsRoute
  '/inventory/receiving': typeof AuthenticatedInventoryReceivingRoute
  '/mobile/counting': typeof AuthenticatedMobileCountingRoute
  '/mobile/picking': typeof AuthenticatedMobilePickingRoute
  '/mobile/receiving': typeof AuthenticatedMobileReceivingRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/orders/create': typeof AuthenticatedOrdersCreateRoute
  '/orders/fulfillment': typeof AuthenticatedOrdersFulfillmentRoute
  '/pipeline/$opportunityId': typeof AuthenticatedPipelineOpportunityIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRouteWithChildren
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/reports/pipeline-forecast': typeof AuthenticatedReportsPipelineForecastRoute
  '/settings/api-tokens': typeof AuthenticatedSettingsApiTokensRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/mobile': typeof AuthenticatedMobileIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/pipeline': typeof AuthenticatedPipelineIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/customers/$customerId/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesIndexRoute
  '/customers/segments': typeof AuthenticatedCustomersSegmentsIndexRoute
  '/reports/customers': typeof AuthenticatedReportsCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/customers/communications': typeof AuthenticatedCustomersCommunicationsRoute
  '/_authenticated/customers/duplicates': typeof AuthenticatedCustomersDuplicatesRoute
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/inventory/$itemId': typeof AuthenticatedInventoryItemIdRoute
  '/_authenticated/inventory/alerts': typeof AuthenticatedInventoryAlertsRoute
  '/_authenticated/inventory/analytics': typeof AuthenticatedInventoryAnalyticsRoute
  '/_authenticated/inventory/counts': typeof AuthenticatedInventoryCountsRoute
  '/_authenticated/inventory/dashboard': typeof AuthenticatedInventoryDashboardRoute
  '/_authenticated/inventory/forecasting': typeof AuthenticatedInventoryForecastingRoute
  '/_authenticated/inventory/locations': typeof AuthenticatedInventoryLocationsRoute
  '/_authenticated/inventory/receiving': typeof AuthenticatedInventoryReceivingRoute
  '/_authenticated/mobile/counting': typeof AuthenticatedMobileCountingRoute
  '/_authenticated/mobile/picking': typeof AuthenticatedMobilePickingRoute
  '/_authenticated/mobile/receiving': typeof AuthenticatedMobileReceivingRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/orders/create': typeof AuthenticatedOrdersCreateRoute
  '/_authenticated/orders/fulfillment': typeof AuthenticatedOrdersFulfillmentRoute
  '/_authenticated/pipeline/$opportunityId': typeof AuthenticatedPipelineOpportunityIdRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRouteWithChildren
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/reports/pipeline-forecast': typeof AuthenticatedReportsPipelineForecastRoute
  '/_authenticated/settings/api-tokens': typeof AuthenticatedSettingsApiTokensRoute
  '/_authenticated/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/_authenticated/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/mobile/': typeof AuthenticatedMobileIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/pipeline/': typeof AuthenticatedPipelineIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/customers/$customerId_/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/_authenticated/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/_authenticated/admin/activities/': typeof AuthenticatedAdminActivitiesIndexRoute
  '/_authenticated/customers/segments/': typeof AuthenticatedCustomersSegmentsIndexRoute
  '/_authenticated/reports/customers/': typeof AuthenticatedReportsCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/customers/$customerId'
    | '/customers/communications'
    | '/customers/duplicates'
    | '/customers/new'
    | '/inventory/$itemId'
    | '/inventory/alerts'
    | '/inventory/analytics'
    | '/inventory/counts'
    | '/inventory/dashboard'
    | '/inventory/forecasting'
    | '/inventory/locations'
    | '/inventory/receiving'
    | '/mobile/counting'
    | '/mobile/picking'
    | '/mobile/receiving'
    | '/orders/$orderId'
    | '/orders/create'
    | '/orders/fulfillment'
    | '/pipeline/$opportunityId'
    | '/products/$productId'
    | '/products/new'
    | '/reports/pipeline-forecast'
    | '/settings/api-tokens'
    | '/settings/categories'
    | '/activities/'
    | '/customers/'
    | '/inventory/'
    | '/mobile/'
    | '/orders/'
    | '/pipeline/'
    | '/products/'
    | '/customers/$customerId/edit'
    | '/products/$productId/edit'
    | '/admin/activities/'
    | '/customers/segments/'
    | '/reports/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/customers/$customerId'
    | '/customers/communications'
    | '/customers/duplicates'
    | '/customers/new'
    | '/inventory/$itemId'
    | '/inventory/alerts'
    | '/inventory/analytics'
    | '/inventory/counts'
    | '/inventory/dashboard'
    | '/inventory/forecasting'
    | '/inventory/locations'
    | '/inventory/receiving'
    | '/mobile/counting'
    | '/mobile/picking'
    | '/mobile/receiving'
    | '/orders/$orderId'
    | '/orders/create'
    | '/orders/fulfillment'
    | '/pipeline/$opportunityId'
    | '/products/$productId'
    | '/products/new'
    | '/reports/pipeline-forecast'
    | '/settings/api-tokens'
    | '/settings/categories'
    | '/activities'
    | '/customers'
    | '/inventory'
    | '/mobile'
    | '/orders'
    | '/pipeline'
    | '/products'
    | '/customers/$customerId/edit'
    | '/products/$productId/edit'
    | '/admin/activities'
    | '/customers/segments'
    | '/reports/customers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/logout'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/customers/communications'
    | '/_authenticated/customers/duplicates'
    | '/_authenticated/customers/new'
    | '/_authenticated/inventory/$itemId'
    | '/_authenticated/inventory/alerts'
    | '/_authenticated/inventory/analytics'
    | '/_authenticated/inventory/counts'
    | '/_authenticated/inventory/dashboard'
    | '/_authenticated/inventory/forecasting'
    | '/_authenticated/inventory/locations'
    | '/_authenticated/inventory/receiving'
    | '/_authenticated/mobile/counting'
    | '/_authenticated/mobile/picking'
    | '/_authenticated/mobile/receiving'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/orders/create'
    | '/_authenticated/orders/fulfillment'
    | '/_authenticated/pipeline/$opportunityId'
    | '/_authenticated/products/$productId'
    | '/_authenticated/products/new'
    | '/_authenticated/reports/pipeline-forecast'
    | '/_authenticated/settings/api-tokens'
    | '/_authenticated/settings/categories'
    | '/_authenticated/activities/'
    | '/_authenticated/customers/'
    | '/_authenticated/inventory/'
    | '/_authenticated/mobile/'
    | '/_authenticated/orders/'
    | '/_authenticated/pipeline/'
    | '/_authenticated/products/'
    | '/_authenticated/customers/$customerId_/edit'
    | '/_authenticated/products/$productId/edit'
    | '/_authenticated/admin/activities/'
    | '/_authenticated/customers/segments/'
    | '/_authenticated/reports/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline/': {
      id: '/_authenticated/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof AuthenticatedPipelineIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mobile/': {
      id: '/_authenticated/mobile/'
      path: '/mobile'
      fullPath: '/mobile/'
      preLoaderRoute: typeof AuthenticatedMobileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activities/': {
      id: '/_authenticated/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof AuthenticatedActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/categories': {
      id: '/_authenticated/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthenticatedSettingsCategoriesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/api-tokens': {
      id: '/_authenticated/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/settings/api-tokens'
      preLoaderRoute: typeof AuthenticatedSettingsApiTokensRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reports/pipeline-forecast': {
      id: '/_authenticated/reports/pipeline-forecast'
      path: '/reports/pipeline-forecast'
      fullPath: '/reports/pipeline-forecast'
      preLoaderRoute: typeof AuthenticatedReportsPipelineForecastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline/$opportunityId': {
      id: '/_authenticated/pipeline/$opportunityId'
      path: '/pipeline/$opportunityId'
      fullPath: '/pipeline/$opportunityId'
      preLoaderRoute: typeof AuthenticatedPipelineOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/fulfillment': {
      id: '/_authenticated/orders/fulfillment'
      path: '/orders/fulfillment'
      fullPath: '/orders/fulfillment'
      preLoaderRoute: typeof AuthenticatedOrdersFulfillmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/create': {
      id: '/_authenticated/orders/create'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof AuthenticatedOrdersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mobile/receiving': {
      id: '/_authenticated/mobile/receiving'
      path: '/mobile/receiving'
      fullPath: '/mobile/receiving'
      preLoaderRoute: typeof AuthenticatedMobileReceivingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mobile/picking': {
      id: '/_authenticated/mobile/picking'
      path: '/mobile/picking'
      fullPath: '/mobile/picking'
      preLoaderRoute: typeof AuthenticatedMobilePickingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mobile/counting': {
      id: '/_authenticated/mobile/counting'
      path: '/mobile/counting'
      fullPath: '/mobile/counting'
      preLoaderRoute: typeof AuthenticatedMobileCountingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/receiving': {
      id: '/_authenticated/inventory/receiving'
      path: '/inventory/receiving'
      fullPath: '/inventory/receiving'
      preLoaderRoute: typeof AuthenticatedInventoryReceivingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/locations': {
      id: '/_authenticated/inventory/locations'
      path: '/inventory/locations'
      fullPath: '/inventory/locations'
      preLoaderRoute: typeof AuthenticatedInventoryLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/forecasting': {
      id: '/_authenticated/inventory/forecasting'
      path: '/inventory/forecasting'
      fullPath: '/inventory/forecasting'
      preLoaderRoute: typeof AuthenticatedInventoryForecastingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/dashboard': {
      id: '/_authenticated/inventory/dashboard'
      path: '/inventory/dashboard'
      fullPath: '/inventory/dashboard'
      preLoaderRoute: typeof AuthenticatedInventoryDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/counts': {
      id: '/_authenticated/inventory/counts'
      path: '/inventory/counts'
      fullPath: '/inventory/counts'
      preLoaderRoute: typeof AuthenticatedInventoryCountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/analytics': {
      id: '/_authenticated/inventory/analytics'
      path: '/inventory/analytics'
      fullPath: '/inventory/analytics'
      preLoaderRoute: typeof AuthenticatedInventoryAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/alerts': {
      id: '/_authenticated/inventory/alerts'
      path: '/inventory/alerts'
      fullPath: '/inventory/alerts'
      preLoaderRoute: typeof AuthenticatedInventoryAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/$itemId': {
      id: '/_authenticated/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof AuthenticatedInventoryItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/duplicates': {
      id: '/_authenticated/customers/duplicates'
      path: '/customers/duplicates'
      fullPath: '/customers/duplicates'
      preLoaderRoute: typeof AuthenticatedCustomersDuplicatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/communications': {
      id: '/_authenticated/customers/communications'
      path: '/customers/communications'
      fullPath: '/customers/communications'
      preLoaderRoute: typeof AuthenticatedCustomersCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/customers/': {
      id: '/_authenticated/reports/customers/'
      path: '/reports/customers'
      fullPath: '/reports/customers/'
      preLoaderRoute: typeof AuthenticatedReportsCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/segments/': {
      id: '/_authenticated/customers/segments/'
      path: '/customers/segments'
      fullPath: '/customers/segments/'
      preLoaderRoute: typeof AuthenticatedCustomersSegmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/activities/': {
      id: '/_authenticated/admin/activities/'
      path: '/admin/activities'
      fullPath: '/admin/activities/'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$productId/edit': {
      id: '/_authenticated/products/$productId/edit'
      path: '/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRoute
    }
    '/_authenticated/customers/$customerId_/edit': {
      id: '/_authenticated/customers/$customerId_/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsApiTokensRoute: typeof AuthenticatedSettingsApiTokensRoute
  AuthenticatedSettingsCategoriesRoute: typeof AuthenticatedSettingsCategoriesRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsApiTokensRoute: AuthenticatedSettingsApiTokensRoute,
  AuthenticatedSettingsCategoriesRoute: AuthenticatedSettingsCategoriesRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedProductsProductIdRouteChildren {
  AuthenticatedProductsProductIdEditRoute: typeof AuthenticatedProductsProductIdEditRoute
}

const AuthenticatedProductsProductIdRouteChildren: AuthenticatedProductsProductIdRouteChildren =
  {
    AuthenticatedProductsProductIdEditRoute:
      AuthenticatedProductsProductIdEditRoute,
  }

const AuthenticatedProductsProductIdRouteWithChildren =
  AuthenticatedProductsProductIdRoute._addFileChildren(
    AuthenticatedProductsProductIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedCustomersCommunicationsRoute: typeof AuthenticatedCustomersCommunicationsRoute
  AuthenticatedCustomersDuplicatesRoute: typeof AuthenticatedCustomersDuplicatesRoute
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedInventoryItemIdRoute: typeof AuthenticatedInventoryItemIdRoute
  AuthenticatedInventoryAlertsRoute: typeof AuthenticatedInventoryAlertsRoute
  AuthenticatedInventoryAnalyticsRoute: typeof AuthenticatedInventoryAnalyticsRoute
  AuthenticatedInventoryCountsRoute: typeof AuthenticatedInventoryCountsRoute
  AuthenticatedInventoryDashboardRoute: typeof AuthenticatedInventoryDashboardRoute
  AuthenticatedInventoryForecastingRoute: typeof AuthenticatedInventoryForecastingRoute
  AuthenticatedInventoryLocationsRoute: typeof AuthenticatedInventoryLocationsRoute
  AuthenticatedInventoryReceivingRoute: typeof AuthenticatedInventoryReceivingRoute
  AuthenticatedMobileCountingRoute: typeof AuthenticatedMobileCountingRoute
  AuthenticatedMobilePickingRoute: typeof AuthenticatedMobilePickingRoute
  AuthenticatedMobileReceivingRoute: typeof AuthenticatedMobileReceivingRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedOrdersCreateRoute: typeof AuthenticatedOrdersCreateRoute
  AuthenticatedOrdersFulfillmentRoute: typeof AuthenticatedOrdersFulfillmentRoute
  AuthenticatedPipelineOpportunityIdRoute: typeof AuthenticatedPipelineOpportunityIdRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRouteWithChildren
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedReportsPipelineForecastRoute: typeof AuthenticatedReportsPipelineForecastRoute
  AuthenticatedActivitiesIndexRoute: typeof AuthenticatedActivitiesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedMobileIndexRoute: typeof AuthenticatedMobileIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedPipelineIndexRoute: typeof AuthenticatedPipelineIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedCustomersCustomerIdEditRoute: typeof AuthenticatedCustomersCustomerIdEditRoute
  AuthenticatedAdminActivitiesIndexRoute: typeof AuthenticatedAdminActivitiesIndexRoute
  AuthenticatedCustomersSegmentsIndexRoute: typeof AuthenticatedCustomersSegmentsIndexRoute
  AuthenticatedReportsCustomersIndexRoute: typeof AuthenticatedReportsCustomersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedCustomersCommunicationsRoute:
    AuthenticatedCustomersCommunicationsRoute,
  AuthenticatedCustomersDuplicatesRoute: AuthenticatedCustomersDuplicatesRoute,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedInventoryItemIdRoute: AuthenticatedInventoryItemIdRoute,
  AuthenticatedInventoryAlertsRoute: AuthenticatedInventoryAlertsRoute,
  AuthenticatedInventoryAnalyticsRoute: AuthenticatedInventoryAnalyticsRoute,
  AuthenticatedInventoryCountsRoute: AuthenticatedInventoryCountsRoute,
  AuthenticatedInventoryDashboardRoute: AuthenticatedInventoryDashboardRoute,
  AuthenticatedInventoryForecastingRoute:
    AuthenticatedInventoryForecastingRoute,
  AuthenticatedInventoryLocationsRoute: AuthenticatedInventoryLocationsRoute,
  AuthenticatedInventoryReceivingRoute: AuthenticatedInventoryReceivingRoute,
  AuthenticatedMobileCountingRoute: AuthenticatedMobileCountingRoute,
  AuthenticatedMobilePickingRoute: AuthenticatedMobilePickingRoute,
  AuthenticatedMobileReceivingRoute: AuthenticatedMobileReceivingRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedOrdersCreateRoute: AuthenticatedOrdersCreateRoute,
  AuthenticatedOrdersFulfillmentRoute: AuthenticatedOrdersFulfillmentRoute,
  AuthenticatedPipelineOpportunityIdRoute:
    AuthenticatedPipelineOpportunityIdRoute,
  AuthenticatedProductsProductIdRoute:
    AuthenticatedProductsProductIdRouteWithChildren,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedReportsPipelineForecastRoute:
    AuthenticatedReportsPipelineForecastRoute,
  AuthenticatedActivitiesIndexRoute: AuthenticatedActivitiesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedMobileIndexRoute: AuthenticatedMobileIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedPipelineIndexRoute: AuthenticatedPipelineIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedCustomersCustomerIdEditRoute:
    AuthenticatedCustomersCustomerIdEditRoute,
  AuthenticatedAdminActivitiesIndexRoute:
    AuthenticatedAdminActivitiesIndexRoute,
  AuthenticatedCustomersSegmentsIndexRoute:
    AuthenticatedCustomersSegmentsIndexRoute,
  AuthenticatedReportsCustomersIndexRoute:
    AuthenticatedReportsCustomersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
